[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
regex = "1.11.1"
rayon = "1.6"
itertools = "0.14.0"
minilp = "0.2"